// <auto-generated />
namespace DataModel.RestorauntContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddIngredients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIngredients));
        
        string IMigrationMetadata.Id
        {
            get { return "201602211933441_AddIngredients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
